# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'CAC XML reader' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CAC XML reader
pod 'Firebase'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Firebase/Crash'
pod 'Firebase/RemoteConfig'

end
